# Generated by Django 2.1.5 on 2019-11-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBV', '0002_auto_20191111_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dob',
        ),
    ]
