# Generated by Django 2.1.5 on 2021-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='confirmPassword',
            field=models.TextField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.TextField(default='', max_length=15),
        ),
    ]
