# Generated by Django 2.1.5 on 2021-09-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20210928_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='confirmPassword',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
