# Generated by Django 4.0.6 on 2022-08-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pro_img')),
                ('title', models.CharField(default='', max_length=20)),
                ('price', models.PositiveIntegerField(default='')),
                ('description', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='', max_length=10)),
                ('oemail', models.EmailField(default='', max_length=254)),
                ('name', models.CharField(default='', max_length=25)),
                ('services', models.CharField(default='', max_length=500)),
                ('adddress', models.CharField(default='', max_length=200)),
                ('contact', models.CharField(default='', max_length=11)),
                ('service_date', models.DateField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
            ],
        ),
        migrations.CreateModel(
            name='DonateMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signup')),
            ],
        ),
    ]
