# Generated by Django 2.1.5 on 2021-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pro_img')),
                ('title', models.CharField(default='', max_length=20)),
                ('price', models.PositiveIntegerField(default='')),
                ('description', models.CharField(default='', max_length=90)),
            ],
        ),
    ]
