# Generated by Django 2.1.5 on 2021-10-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210928_2254'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signUp')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=80)),
                ('ordered_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('qrimage', models.ImageField(blank=True, null=True, upload_to='qrimage')),
                ('invoice', models.FileField(default='', upload_to='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.signUp')),
            ],
        ),
    ]
