# Generated by Django 2.1.5 on 2021-11-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20210928_2254'),
        ('categories', '0005_auto_20211127_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.signUp')),
            ],
        ),
    ]
