# Generated by Django 4.0.6 on 2022-08-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.PositiveIntegerField(default='')),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='inputmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputA', models.IntegerField(default='')),
                ('inputB', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='mainItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pro_img')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='xyz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.PositiveIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=255)),
                ('descriptionOfCategory', models.TextField()),
                ('priceOfProduct', models.IntegerField(default='')),
                ('registration_date', models.DateField()),
                ('rating', models.IntegerField(default='')),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category11')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pro_img')),
                ('title', models.CharField(default='', max_length=20)),
                ('price', models.PositiveIntegerField(default='')),
                ('description', models.CharField(default='', max_length=90)),
                ('categoryName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.mainitem')),
            ],
        ),
    ]
