# Generated by Django 2.1.5 on 2021-09-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=255)),
                ('descriptionOfCategory', models.TextField()),
                ('priceOfProduct', models.IntegerField(default='')),
                ('registration_date', models.DateField()),
                ('rating', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='CategoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Owner'),
        ),
    ]
