# Generated by Django 2.1.5 on 2021-09-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(max_length=255)),
                ('descriptionOfCategory', models.TextField()),
                ('priceOfProduct', models.IntegerField(default='')),
                ('registration_date', models.DateField()),
                ('rating', models.IntegerField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='CategoryName',
        ),
        migrations.RemoveField(
            model_name='category',
            name='descriptionOfCategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ownerName',
        ),
        migrations.RemoveField(
            model_name='category',
            name='priceOfProduct',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='category',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='product',
            name='CategoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Category'),
        ),
    ]
