# Generated by Django 2.1.5 on 2021-09-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_xyz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xyz',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='xyz',
            name='name',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='xyz',
            name='number',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
