# Generated by Django 2.1.5 on 2021-10-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20211001_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
