# Generated by Django 2.1.5 on 2021-10-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, upload_to='pro_img'),
        ),
    ]
