# Generated by Django 2.1.5 on 2021-10-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_item_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputA', models.IntegerField(default='')),
                ('inputB', models.IntegerField(default='')),
            ],
        ),
    ]
