# Generated by Django 2.1.5 on 2021-10-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactForm',
        ),
    ]
