# Generated by Django 2.1.5 on 2021-10-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20211008_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pro_img')),
                ('title', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=90)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='categoryName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.mainItem'),
        ),
    ]
